---
- name: Install software and copy settings for "{{username}}"
  hosts: target_server
  gather_facts: yes
  become: yes
  
  vars:
    ansible_user: zx
    username: zx

  tasks:
    - name: Create keyrings directory
      ansible.builtin.file:
        path: /etc/apt/keyrings
        state: directory
        mode: '0755'
      become: yes
      tags: docker-addrepo

    - name: Download Docker GPG key
      ansible.builtin.get_url:
        url: https://download.docker.com/linux/debian/gpg
        dest: /etc/apt/keyrings/docker.asc
        mode: '0644'
      become: yes
      tags: docker-addrepo

    - name: Ensure Docker GPG key is readable
      ansible.builtin.file:
        path: /etc/apt/keyrings/docker.asc
        mode: '0644'
      become: yes
      tags: docker-addrepo

    - name: add docker repository to apt
      apt_repository:
        repo: "deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/debian bookworm stable"
        state: present
        filename: docker
      become: yes
      tags: docker-addrepo

    - name: Update apt cache
      apt:
        update_cache: yes
      become: yes
      tags: docker-addrepo

    - name: install docker
      apt:
        name: "{{item}}"
        state: latest
        update_cache: yes
      loop:
        - docker-ce
        - docker-ce-cli
        - containerd.io
        - docker-buildx-plugin
        - docker-compose-plugin
      become: yes
      tags: docker-install

    - name: check docker is active
      service:
        name: docker
      tags: docker-check


    - name: Add "{{username}}" to docker group
      ansible.builtin.user:
        name: "{{username}}"
        groups: docker
        append: yes
      become: yes
      tags: docker-group

