[custom.loadavg]
command = """
# Путь к скрипту - замените на актуальный путь
/Users/kd/projects/personal/environment/script.sh
"""
when = ""
# Используем регулярное выражение для обработки вывода скрипта
# Если вывод начинается с "low|", применяем зеленый стиль и иконку
# Если вывод начинается с "high|", применяем красный стиль и иконку
format = """
$output
"""
style = "bg:color_bg1"

# Используем регулярное выражение для замены вывода скрипта
# Если вывод начинается с "low|", заменяем на зеленую иконку и значение
# Если вывод начинается с "high|", заменяем на красную иконку и значение
[custom.loadavg.map_output]
"low\\|(.+)" = "[](fg:color_bg2 bg:color_bg1)[ 󰾆 $1 ](fg:color_green bg:color_bg1)"
"high\\|(.+)" = "[](fg:color_bg2 bg:color_bg1)[ 󰓅 $1 ](fg:color_red bg:color_bg1)"
